// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0kkcnt_nMEnGcoGYziScS93Um3XPOimM',
    appId: '1:941590347459:android:900334d20da2a5aaadec76',
    messagingSenderId: '941590347459',
    projectId: 'lets-padel-club-lb',
    storageBucket: 'lets-padel-club-lb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZSEh1Qfn8qxr2le5c8aLmyo1lk75HT0',
    appId: '1:941590347459:web:4fcd8c1083b50f99adec76',
    messagingSenderId: '941590347459',
    projectId: 'lets-padel-club-lb',
    authDomain: 'lets-padel-club-lb.firebaseapp.com',
    storageBucket: 'lets-padel-club-lb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGxHJLeOBFTjALruzNwDpCGWdBs_a96nI',
    appId: '1:941590347459:ios:d39a1727e4e0572fadec76',
    messagingSenderId: '941590347459',
    projectId: 'lets-padel-club-lb',
    storageBucket: 'lets-padel-club-lb.firebasestorage.app',
    androidClientId:
        '941590347459-b2097te1upa3tj36mad9l099f4hdp1s9.apps.googleusercontent.com',
    iosClientId:
        '941590347459-35vrrb13vm7lreujofmvhkl6rt3ko97g.apps.googleusercontent.com',
    iosBundleId: 'com.padelclub.padelApp',
  );
}
